# --
# config file for this project


# --
# audio dataset config
audio_dataset:

  # path to speech command dataset
  dataset_path: ./ignore/dataset/speech_commands_v0.01/

  # paths to save training, testing and eval data
  data_paths:
    - ./ignore/dataset/train/
    - ./ignore/dataset/test/
    - ./ignore/dataset/eval/

  # wav folder name
  wav_folder: wavs/

  # plot path root
  plot_paths:
    mfcc: ./ignore/plots/features/mfcc/
    z_score: ./ignore/plots/features/z_score/

  # enable plot of each feature extraction
  #enable_plot: True
  enable_plot: False

  # split of dataset in training, test, eval (must be a prob. distribution)
  data_percs: [0.8, 0.1, 0.1]

  # selected labels of the whole set
  sel_labels: ['left', 'right', 'up', 'down', 'go']
  #sel_labels = ['eight', 'sheila', 'nine', 'yes', 'one', 'no', 'left', 'tree', 'bed', 'bird', 'go', 'wow', 'seven', 'marvin', 'dog', 'three', 'two', 'house', 'down', 'six', 'five', 'off', 'right', 'cat', 'zero', 'four', 'stop', 'up', 'on', 'happy']

  # version number - just to confuse myself not too much
  # v3: data extraction with min energy and randomize onsets
  version_nr: 3

  # number of examples picked from dataset
  #n_examples: 10
  n_examples: 500


# --
# feature params
feature_params:

  # sampling rate
  fs: 16000

  # window and hop size [sec]
  N_s: 0.025
  hop_s: 0.010

  # number of filter bands and cepstral coeffs
  n_filter_bands: 32
  n_ceps_coeff: 12

  # frame size of output features -> input to nn
  frame_size: 32

  # mfcc feat size - do not change this
  feature_size: 39


# --
# my recording stuff
my_recordings:

  # paths
  out_path: ./ignore/my_recordings/
  in_path: ./ignore/my_recordings/raw/
  plot_path: ./ignore/my_recordings/plots/
  wav_path: ./ignore/my_recordings/wavs/

  # my recordins set name
  set_name: 'my'

  # enable plot
  enable_plot: False

  # force recut of recordings
  recut: False


# --
# game settings
game:

  # frames per seconds
  fps: 60

  # size of display
  screen_size: [640, 480]

  # enabled flag
  capture_enabled: False

  # capture path
  capture_path: ./ignore/capture/


# --
# classifier
classifier:

  # file name
  file: './models/fstride_c-5.npz'

  # verbose
  verbose: False


# --
# ml
ml:

  # c-5
  #mfcc_data_files: ['./ignore/dataset/train/mfcc_data_train_n-2000_c-5_v3.npz', './ignore/dataset/test/mfcc_data_test_n-2000_c-5_v3.npz', './ignore/dataset/eval/mfcc_data_eval_n-2000_c-5_v3.npz', './ignore/my_recordings/mfcc_data_my_n-25_c-5_v3.npz']
  mfcc_data_files: ['./ignore/dataset/train/mfcc_data_train_n-500_c-5_v3.npz', './ignore/dataset/test/mfcc_data_test_n-500_c-5_v3.npz', './ignore/dataset/eval/mfcc_data_eval_n-500_c-5_v3.npz', './ignore/my_recordings/mfcc_data_my_n-25_c-5_v3.npz']

  # c-30
  #mfcc_data_files: ['./ignore/dataset/train/mfcc_data_train_n-2000_c-5_v3.npz', './ignore/dataset/test/mfcc_data_test_n-2000_c-5_v3.npz', './ignore/dataset/eval/mfcc_data_eval_n-2000_c-5_v3.npz', './ignore/my_recordings/mfcc_data_my_n-25_c-5_v3.npz']
  
  # paths
  plot_path: ./ignore/plots/ml/
  shift_path: ./ignore/plots/ml/shift/
  metric_path: ./ignore/plots/ml/metrics/' 
  model_path: ./ignore/models/ 
  model_pre_path: ./ignore/models/pre/ 
  log_path: ./ignore/logs/

  # params
  params:

    # batch size
    batch_size: 32

    # number of epochs
    num_epochs: 500

    # learning rate
    lr: 0.0001

  # retrain existing model
  retrain: False

  # nn architecture available
  nn_architectures: {1: 'conv-trad', 2: 'conv-fstride'}

  # chosen architecture
  nn_arch: conv-trad


  # pretrained model
  #pre_trained_model_path = model_pre_path + 'conv-fstride_c-30.pth'
  #pre_trained_model_path = None








